import Link from 'next/link'

const TIERS = [
  {
    name: 'Free',
    price: '$0',
    period: 'forever',
    desc: 'Get started and see what a personalized path looks like.',
    cta: 'Get Started Free',
    href: '/onboarding',
    accent: false,
    features: [
      'Personalized learning path generated by AI',
      'First 2 modules unlocked',
      'Basic resource links',
      'No projects included',
    ],
    missing: ['Full curriculum access', 'Guided projects', 'Monthly new content', 'Ask questions'],
  },
  {
    name: 'Starter',
    price: '$19',
    period: 'one-time',
    desc: 'Everything you need to complete your full AI learning journey.',
    cta: 'Get Starter',
    href: '/onboarding?tier=starter',
    accent: true,
    badge: 'Most Popular',
    features: [
      'Full personalized curriculum (all modules)',
      '3 guided hands-on projects',
      'Curated resources for every module',
      'Progress tracking',
      'One-time payment, yours forever',
    ],
    missing: ['Monthly new projects', 'Ask questions feature'],
  },
  {
    name: 'Pro',
    price: '$29',
    period: 'per month',
    desc: 'For serious learners who want a continuously updated experience.',
    cta: 'Get Pro',
    href: '/onboarding?tier=pro',
    accent: false,
    features: [
      'Everything in Starter',
      'New hands-on projects every month',
      'Ask AI questions about your path',
      'Priority path regeneration',
      'Early access to new features',
    ],
    missing: [],
  },
]

const FAQ = [
  { q: "Can I upgrade later?", a: "Yes — generate a free path first, then upgrade at any time from your results page." },
  { q: "What does 'personalized' actually mean?", a: "Claude analyzes your skill level, goals, time, learning style, and domain interest to build a curriculum specifically for you — not a generic template." },
  { q: "Are the resources free?", a: "We curate a mix of free and paid resources. Most are free (YouTube, fast.ai, Hugging Face, arXiv). Paid ones are clearly marked." },
  { q: "Is there a refund policy?", a: "Yes — if you're not happy with your Starter path, email us within 7 days for a full refund." },
  { q: "Can I generate multiple paths?", a: "Yes. Each path generation is separate. Dashboard saves all your paths locally." },
]

export default function Pricing() {
  return (
    <div className="min-h-screen">
      <nav className="px-6 py-5 border-b border-[var(--border)] flex items-center justify-between">
        <Link href="/" className="text-lg font-bold"><span className="gradient-text">Campio</span></Link>
        <Link href="/onboarding" className="px-4 py-2 rounded-lg bg-[var(--accent)] text-white text-sm font-semibold hover:bg-[var(--accent2)] transition-colors">Get Started</Link>
      </nav>

      <div className="max-w-5xl mx-auto px-6 py-20">
        <div className="text-center mb-16">
          <p className="text-xs font-bold uppercase tracking-widest text-[var(--accent)] mb-3">Pricing</p>
          <h1 className="text-5xl font-extrabold tracking-tight mb-4">Simple, honest pricing</h1>
          <p className="text-lg text-[var(--muted)] max-w-xl mx-auto">Start free. Upgrade when you're ready to go deep. No subscriptions required unless you want ongoing content.</p>
        </div>

        {/* Cards */}
        <div className="grid md:grid-cols-3 gap-6 mb-20">
          {TIERS.map(tier => (
            <div key={tier.name} className={`rounded-2xl border p-8 flex flex-col relative ${tier.accent ? 'border-[var(--accent)] bg-[rgba(124,106,255,0.06)]' : 'border-[var(--border)] bg-[var(--surface)]'}`}>
              {tier.badge && (
                <div className="absolute -top-3 left-1/2 -translate-x-1/2 px-3 py-1 rounded-full bg-[var(--accent)] text-white text-xs font-bold whitespace-nowrap">
                  {tier.badge}
                </div>
              )}
              <div className="mb-6">
                <h2 className="text-xl font-bold mb-1">{tier.name}</h2>
                <div className="flex items-baseline gap-1 mb-2">
                  <span className="text-4xl font-extrabold">{tier.price}</span>
                  <span className="text-[var(--muted)] text-sm">/ {tier.period}</span>
                </div>
                <p className="text-sm text-[var(--muted)]">{tier.desc}</p>
              </div>
              <ul className="space-y-3 mb-6 flex-1">
                {tier.features.map(f => (
                  <li key={f} className="flex items-start gap-2 text-sm">
                    <span className="text-[var(--green)] mt-0.5 flex-shrink-0">✓</span>
                    <span>{f}</span>
                  </li>
                ))}
                {tier.missing.map(f => (
                  <li key={f} className="flex items-start gap-2 text-sm text-[var(--muted)]">
                    <span className="mt-0.5 flex-shrink-0">✗</span>
                    <span>{f}</span>
                  </li>
                ))}
              </ul>
              <Link href={tier.href}
                className={`w-full py-3 rounded-xl font-bold text-center transition-all hover:-translate-y-0.5 ${tier.accent ? 'bg-[var(--accent)] text-white hover:bg-[var(--accent2)]' : 'border border-[var(--border)] text-[var(--text)] hover:border-[var(--accent)] hover:text-[var(--accent)]'}`}>
                {tier.cta}
              </Link>
            </div>
          ))}
        </div>

        {/* FAQ */}
        <div className="max-w-2xl mx-auto">
          <h2 className="text-3xl font-bold text-center mb-10">Frequently asked questions</h2>
          <div className="space-y-4">
            {FAQ.map(f => (
              <div key={f.q} className="rounded-xl border border-[var(--border)] bg-[var(--surface)] p-6">
                <h3 className="font-semibold mb-2">{f.q}</h3>
                <p className="text-[var(--muted)] text-sm leading-relaxed">{f.a}</p>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  )
}
